### ISSUE TITLE
Yeelight color4 Return unparsable error message when calling get_prop

### ISSUE THREAD

**Issue by Simjen** [song940/node-yeelight#13]
I was trying to connect to my yeelight color4 using node-red. But it seems like if the "active_mode" property is present in the params array for get_prop then the bulp return an unparsable error message: {"id":, "error":{"code":-1, "message":"invalid command"}}. It might be a yeelight issue but maybe something can be done to alliviate this problem, Such that syncing the bulp will not crash the application? everything works if i comment out "active_mode" in the prop array at index.js line 163.

**Comment by lsongdev** [comment]
https://github.com/song940/node-yeelight/issues/12
