### ISSUE TITLE
Error with version 1.3.7 and Celling light

### ISSUE THREAD

**Issue by jpg06** [song940/node-yeelight#15]
Hi,
I have an error message with the last version 1.3.7.
I have test on two installations and a have the same result with Yeelight Celling light (it's ok with Bulb).
The error message is:
     _UnhandledPromiseRejectionWarning: Error: Network timeout, Yeelight not response
          at Timeout._onTimeout (/home/nodered/jpgDomotique/node-red-contrib-yeelight-compat-hue/node_modules/yeelight2/index.js:231:29)
     at listOnTimeout (internal/timers.js:549:17)
     at processTimers (internal/timers.js:492:7)_

I get this error for each celling light.

I made some tests and i found that if i comment two "props" in index.js (for example "flowing" and "flow_params" in Yeelight.prototype.props=[...] ), all is working like in older version.
The props values commented is not important: it is the number of props which is important.

Can you make a correction to solve the problem ?

**Comment by lsongdev** [comment]
https://github.com/song940/node-yeelight/issues/13

**Comment by jpg06** [comment]
I think I've found a way to resolve this error, even if it's not the best solution.
