### ISSUE TITLE
Error: read ECONNRESET not handled with .catch()

### ISSUE THREAD

**Issue by 0rsa** [song940/node-yeelight#16]
Hello,

I use:
nodejs 15.12.0 
node-red 1.2.9
node-red-contrib-yeelight 1.0.7

I got this error after a while:

> 28 Mar 17:13:42 - [error] [yeelight-config:5f497ad3.1fd3a4] Error: read ECONNRESET
> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> Error: Network timeout, Yeelight not response
>     at Timeout._onTimeout (/root/.node-red/node_modules/yeelight2/index.js:230:29)
>     at listOnTimeout (node:internal/timers:557:17)
>     at processTimers (node:internal/timers:500:7)

Can you check?
Thank you

**Comment by udany** [comment]
@0rsa I see you closed this, did you figure out how to handle the error?

**Comment by udany** [comment]
fyi, in case someone ever stumbles upon this, it's pretty simple:

Just make sure to bind a listener to the error event on your socket: `socket.on('error', () => {...})`
