### ISSUE TITLE
Unhandled promise rejection: timeout/[object Object]

### ISSUE THREAD

**Issue by unm4sk1g** [song940/node-yeelight#4]
This issue happens after changing colors of the Yeelight (I guess it's E27, RGB definitely) Lightbulb too fast. 
```
(node:13721) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): [object Object]
(node:13721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
After adding set DEBUG=yeelight to CLI parameters:
```
Error: timeout
    at Timeout._onTimeout (/home/unm4sk/Desktop/homeserver-dev/node_modules/yeelight2/index.js:167:16)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

This sometimes causes the Yeelight Lightbulb itself to freeze, so it's not discoverable anymore until I turn it off and on again (in this case unscrew/screw). Can anything be done about this?

**Comment by lsongdev** [comment]
emm..., Yeelight is a Iot device running at ESP8266 like platform, it include a slow frequency chip, it can not be defence DDOS like you do .
