### ISSUE TITLE
how can i get the status?

### ISSUE THREAD

**Issue by buzai** [song940/node-yeelight#5]

**Comment by lsongdev** [comment]
You can use [yeelight#get_prop](https://github.com/song940/node-yeelight/blob/master/index.js#L200) with like power, bright and [more](https://github.com/song940/node-yeelight/blob/master/index.js#L97) .


```js
const powerStatus = await yeelight.get_prop('power');
console.log(powerStatus); // -> "on"
```

**Comment by buzai** [comment]
@song940 thank u

**Comment by buzai** [comment]
there is some error

```
const Yeelight = require('yeelight2');
async function main() {
  console.log('get status');
  const powerStatus =  Yeelight.get_prop('power');
  console.log(powerStatus); // -> "on"
}
main()
```

when i try node app.js

```
get status
(node:2129) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Yeelight.get_prop is not a function
(node:2129) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lsongdev** [comment]
get_prop is a instance method of Yeelight class, you should create or discover the light object before using it. FYI https://github.com/song940/node-yeelight/blob/master/example/index.js

**Comment by buzai** [comment]
lol i am too foo, now i know how to get the status .
i find when discover the device must use a callback, why not return a promise?
```
function discover() {
  return new Promise(function(resolve, reject) {
    Yeelight.discover(function(light) {
      if (light) {
        resolve(light)
      } else {
        reject(null)
      }
    })
  });
}
```

**Comment by lsongdev** [comment]
because Yeelight.discover can find one or more light in the network, but promise only have once resolved.

**Comment by buzai** [comment]
@song940 
1. You mean the process of discovery can be discontinuous? Once new intelligence is added to the network, it triggers the response event and calls the callback function once, isn't it?

2. in your code , i find 
```
var discover = ssdp({ port: port || 1982 }); 
```
i think every time I call the function, I'll bind the port, but when the first call has been bound, it's gone wrong second times
```
Error: bind EADDRINUSE 0.0.0.0:1982
```


```
/**
 * [discover description]
 * @return {[type]} [description]
 */
Yeelight.discover = function(port, callback){
  if(typeof port === 'function'){
    callback = port; port = 1982;
  }
  var yeelights = [];
  var discover = ssdp({ port: port || 1982 });
  discover.on('response', function(response){
    var address = response.headers['Location'];
    console.debug('received response from', address);
    if(address && (!~yeelights.indexOf(address))){
      yeelights.push(address);
      var yeelight = new Yeelight( address );
      yeelight.id = response.headers.id;
      yeelight.on('connect', function(){
        callback.call(discover, this, response);
      });
    };
    
  });
  console.debug('start finding ...');
  return discover.search('wifi_bulb');
};
```

**Comment by lsongdev** [comment]
1. Yes.
2. You only need call the Yeelight function once, ssdp will listen the udp port at 1982 and scan network blub, waiting new device join, callback will be call one or more times.

**Comment by buzai** [comment]
thank u
