### ISSUE TITLE
Response confirmation

### ISSUE THREAD

**Issue by goyzhang** [song940/node-yeelight#6]
Hello,
I've noticed taht there is no response handler after sending a command. The code just ASSUME that the command was accepted. Maybe we could add a listener to keep the state updated based on a actual response.

**Comment by lsongdev** [comment]
No, when send command to yeelight, [we set a task to the queue](https://github.com/song940/node-yeelight/blob/master/index.js#L164) and [waiting blub's response](https://github.com/song940/node-yeelight/blob/master/index.js#L36)
if receive a message from bulb, and [it has "id" attribute](https://github.com/song940/node-yeelight/blob/master/index.js#L134), it's a response message.

**Comment by goyzhang** [comment]
Maybe I didn't get a well understanding of the code, as I didn't see any socket.read after writing...
Thanks, I'll take some time to look into it.

**Comment by lsongdev** [comment]
In node.js, `socket.read` can be `socket.on('data', (buffer) => { ... })` ([net](https://nodejs.org/docs/latest/api/net.html))

**Comment by goyzhang** [comment]
I see, thanks!

**Comment by goyzhang** [comment]
`var id = (Math.random() * 1e3) & 0xff;`
If two commands executed in 3 seconds(timeout period) got the same id, and one of them didn't perform correctly, there might be a cross-impact. Really unlikely though :D @song940

**Comment by lsongdev** [comment]
`Math.random()` is a random number between 0 and 1, and it can be generate in nanoseconds . so, the probability of collision is very low .
